In [1]:
import numpy as np
import tensorflow as tf
import gym
import tqdm
import collections, statistics

2023-03-08 16:48:14.524514: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-08 16:48:14.605676: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-08 16:48:14.605692: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-08 16:48:14.987591: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
env = gym.make("CartPole-v1")
eps = np.finfo(np.float32).eps.item()
n_hidden_unit = 128
n_action_space = env.action_space.n
initial_state, _ = env.reset()
initial_state_shape = initial_state.shape
gamma = 0.99
print(f"initial state shape: {initial_state_shape}")

initial state shape: (4,)


# define model

In [3]:
def get_model():
    """
    The input will be the state
    The output will be 
    (1) action logits, shape 2
    (2) value, shape 1
    """
    inputs = tf.keras.layers.Input(shape=initial_state_shape)
    comm = tf.keras.layers.Dense(n_hidden_unit, activation="relu", name="common")(inputs)
    action_logits = tf.keras.layers.Dense(n_action_space, activation=None, name="output_action_logits")(comm)
    value = tf.keras.layers.Dense(1, activation=None, name="output_value")(comm)
    return tf.keras.Model(inputs, [action_logits, value])
model = get_model()
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 4)]          0           []                               
                                                                                                  
 common (Dense)                 (None, 128)          640         ['input_1[0][0]']                
                                                                                                  
 output_action_logits (Dense)   (None, 2)            258         ['common[0][0]']                 
                                                                                                  
 output_value (Dense)           (None, 1)            129         ['common[0][0]']                 
                                                                                              

2023-03-08 16:48:15.533511: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-08 16:48:15.533677: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-08 16:48:15.533713: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-03-08 16:48:15.533738: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-03-08 16:48:15.533763: W tensorflow/c

# Design training data collection -- very important

In [4]:
def env_step(action: int):
    """
    env.step cannot be call inside tf graph, so we need to convert it to tf function.
    """
    state, reward, done, _, _ = env.step(action)
    return (
        state.astype(np.float32), 
        np.array(reward,dtype=np.float32),
        np.array(done, dtype=np.int32)
    )

def tf_env_step(action):
    return tf.numpy_function(env_step, [action], [tf.float32, tf.float32, tf.int32])

def run_epoch(initial_state, max_steps, model):
    """
    return action probs, estimated values, actual rewards
    """
    action_probs = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
    estimated_values = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
    rewards = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
    state = initial_state
    # tf.range make sure this can be called in a tf graph
    for t in tf.range(max_steps):
        state = tf.expand_dims(state, 0) # add batch dimension
        action_logit, estimated_value = model(state)
        # sample the action
        action = tf.random.categorical(action_logit, num_samples=1, dtype=None, seed=None, name=None)[0,0]
        action_prob = tf.keras.activations.softmax(action_logit) # the first zero is the batch dim
        
        state, reward, done = tf_env_step(action)
        state.set_shape(initial_state_shape)
        
        action_probs = action_probs.write(t, tf.squeeze(action_prob)[action])
        estimated_values = estimated_values.write(t, tf.squeeze(estimated_value))
        rewards = rewards.write(t, tf.squeeze(reward))
        
        if tf.cast(done, tf.bool):
            break
    action_probs = action_probs.stack()
    estimated_values = estimated_values.stack()
    rewards = rewards.stack()
    return action_probs, estimated_values, rewards
    
    

## test the output

In [5]:
initial_state, _ = env.reset()
A = run_epoch(initial_state, 500, model)
A

/home/wei/anaconda3/envs/tf_211/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(<tf.Tensor: shape=(19,), dtype=float32, numpy=
 array([0.50248265, 0.5073823 , 0.4868419 , 0.49275556, 0.49724457,
        0.50416005, 0.50329655, 0.5075689 , 0.48648456, 0.5077627 ,
        0.5138136 , 0.5199265 , 0.47382995, 0.47918737, 0.51597106,
        0.47807068, 0.51872367, 0.47588745, 0.47764164], dtype=float32)>,
 <tf.Tensor: shape=(19,), dtype=float32, numpy=
 array([-1.69189821e-04,  5.43815307e-02,  1.12011455e-01,  5.13284579e-02,
        -1.31513423e-03, -5.45527041e-03, -3.94668197e-04,  5.23516908e-02,
         1.10388279e-01,  5.11532128e-02,  1.08461022e-01,  1.66180730e-01,
         2.24010125e-01,  1.62061080e-01,  1.03708997e-01,  1.61501169e-01,
         1.04573116e-01,  1.63015470e-01,  1.07496031e-01], dtype=float32)>,
 <tf.Tensor: shape=(19,), dtype=float32, numpy=
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], dtype=float32)>)

# Calculate returns from rewards

In [6]:
# this will be called inside a tf function
def calculate_returns(rewards, normalize=tf.constant(True)):
    returns = tf.TensorArray(np.float32, size=0, dynamic_size=True)
    discounted_sum = tf.constant(0.0)
    discounted_sum_shape = discounted_sum.shape
    # cannot use rewards.shape since it will cause None issue. The tf.shape will handle this problem
    for t in tf.range(tf.shape(rewards)[0]-1, -1, -1):
        discounted_sum = discounted_sum * gamma + rewards[t]
        discounted_sum.set_shape(discounted_sum_shape)
        returns = returns.write(t, discounted_sum)
    returns = returns.stack()
    
    if normalize:
        returns = (returns - tf.math.reduce_mean(returns)) / (tf.math.reduce_std(returns) + eps)
    return returns
        
        

## test the output

In [7]:
r = calculate_returns(A[-1])
print(f"raw returns: {r}")
print(f"mean: {tf.math.reduce_mean(r)}")
print(f"std: {tf.math.reduce_std(r)}")

raw returns: [ 1.5966538   1.4292301   1.2601154   1.0892925   0.916744    0.7424526
  0.56640065  0.3885705   0.20894408  0.02750331 -0.15577021 -0.34089494
 -0.5278897  -0.71677333 -0.90756494 -1.1002836  -1.294949   -1.4915807
 -1.6901985 ]
mean: 1.0038677089596604e-07
std: 0.9999999403953552


# Calculate the loss

In [8]:
# The loss will be called inside tf function
huber = tf.losses.Huber(reduction=tf.losses.Reduction.SUM) # the SUM_OVER_BATCH will normalize by batch size
def compute_loss(action_probs, estimated_values, actual_values):
#     expand dim - this is extremly important. Without below, the loss is wrong and the model will not learn anything
    action_probs, estimated_values, actual_values = [
        tf.cond(tf.cast(x.shape.ndims==1, tf.bool), 
                lambda: tf.expand_dims(x,1), 
                lambda: x
               )  for x in (action_probs, estimated_values, actual_values)]
    
    
    advantage = actual_values - estimated_values
#     advantage = actual_values
    log_action = tf.math.log(tf.clip_by_value(action_probs, eps, 1e10))
    loss_actor = - tf.math.reduce_sum(advantage * log_action)
    loss_huber = huber(estimated_values, actual_values)
    loss = loss_actor + loss_huber
    
    return loss, loss_actor, loss_huber
    

## test the output

In [9]:
loss = compute_loss(A[0], A[1], calculate_returns(A[-1]))
loss

(<tf.Tensor: shape=(), dtype=float32, numpy=8.165183>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.3731375>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.538321>)

# Define train step

In [10]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

@tf.function
def train_step(initial_state, max_steps, model, optimizer):
    """
    1. run epoch to collect data
    2. calculate loss
    3. update weights
    """
    with tf.GradientTape() as tape:
        # 1. run epoch to collect data
        action_probs, estimated_values, rewards = run_epoch(initial_state, max_steps, model)
        actual_values = calculate_returns(rewards)
        
        # 2. calculate loss
        loss, loss_actor, loss_huber = compute_loss(action_probs, estimated_values, actual_values)
        
        
    # calculate gradient
    gradient = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradient, model.trainable_variables))
    total_rewards = tf.math.reduce_sum(tf.squeeze(rewards))
    A = (loss, loss_actor, loss_huber)
    return total_rewards, A
        
    

## test output

In [11]:
initial_state, _ = env.reset()
train_step(initial_state, 500, model, optimizer)

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


(<tf.Tensor: shape=(), dtype=float32, numpy=40.0>,
 (<tf.Tensor: shape=(), dtype=float32, numpy=19.939402>,
  <tf.Tensor: shape=(), dtype=float32, numpy=-2.9859664>,
  <tf.Tensor: shape=(), dtype=float32, numpy=22.925367>))

# Run

In [12]:
min_epochs_to_run = 100
max_epochs_to_run = 10000
max_steps_per_epoch = 500
reward_thred = 475
t = tqdm.trange(max_epochs_to_run)
q = collections.deque(maxlen=100)
rewards_history = []
for i in t:
    initial_state, _ = env.reset()
    initial_state = tf.constant(initial_state, dtype=tf.float32)
    epoch_reward, loss = train_step(initial_state, max_steps_per_epoch, model, optimizer)
    epoch_reward = int(epoch_reward)
    rewards_history.append(epoch_reward)
    q.append(epoch_reward)
    avg_rewards = statistics.mean(q)
    t.set_postfix(current_rewards=epoch_reward, avg_rewards=avg_rewards)
    
    if avg_rewards > reward_thred and i > min_epochs_to_run:
        break
    
    

  4%|▍         | 437/10000 [00:28<10:23, 15.35it/s, avg_rewards=477, current_rewards=500] 


In [13]:
epoch_reward

500